apiVersion: v1
kind: Service
metadata:
  name: {{ include "riquet.fullname" . }}
  labels:
    {{- include "riquet.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "riquet.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "riquet.fullname" . }}-headless
  labels:
    {{- include "riquet.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    {{- include "riquet.selectorLabels" . | nindent 4 }}
  ports:
    - name: internal
      port: 8083
      targetPort: internal
